### ISSUE TITLE
Broken dependencies on perl 5.24

### ISSUE THREAD

**Issue by DrHyde** [damil/Data-Domain#2]
FYI you depend on Scalar::Does, which in turn depends on lexical::underscore, which is broken on 5.24, see https://github.com/tobyink/p5-lexical-underscore/issues/3.

You might want to keep an eye on that issue, and re-test when it's fixed.

**Comment by damil** [comment]
Hi,

Thanks for mentioning this issue.
Meanwhil tobyink fixed Scalar::Does, so there is nothing to change in Data::Domain
