### ISSUE TITLE
optional key in Struct but the value can't be undef

### ISSUE THREAD

**Issue by davewood** [damil/Data-Domain#8]
i think im losing my mind here, how do i achieve the following with Data::Domain?

I want to allow `{ }` but `{ name => undef }` should fail.

so `name` can be omitted from the input HASH but it cant be undef.

tests dont seem to cover this case: [t/data-domain.t](https://metacpan.org/release/DAMI/Data-Domain-1.12/source/t/data-domain.t)

## Code
```
use strict;
use warnings;
use feature qw/say/;
use Data::Dumper;
use Data::Domain qw/:all/;

my $domain = Struct(
                     -exclude => '*',
                     -fields => {
                                  name => String(
                                                  -regex => qr/^[a-z0-9]{2,10}$/,
                                                  -optional => 1,
                                                )
                                }
);

my @values = (
    {},
    { name => undef },
);

for my $v (@values) {
    my $err = $domain->inspect($v);
    say '------------';
    print 'input:   ' . Dumper $v;
    print 'success: ';
    say $err ? 'NOTOK' : 'OK';
    print 'details: ' . Dumper $err if $err;
}
```

## output
```
------------
input:   $VAR1 = {};
success: OK
------------
input:   $VAR1 = {
          'name' => undef
        };
success: OK
```

**Comment by damil** [comment]
Hi,

Thanks for your question, it's an interesting challenge.

The doc for "-optional" says "If true, the domain will accept undef, without generating an error message" ... so indeed, `{name => undef}` is accepted. 

The current API for Struct() has no support for differentiating between a hash key containg undef or a hash key being absent. Usually this is not a problem because with %hash = (present => undef), expressions $hash{present} or $hash{absent} produce the same result. But your point is good : it would be nice to have an additional option for checking if a hash key exists or not. I'll try to to add this feature in the next version, but designing the proper API requires some thinking.

Meanwhile, what you can do is to add a condition requiring that all hash values must be defined :

```
my $domain = Struct(
                     -exclude => '*',
                     -fields => {
                                  name => String(
                                                  -regex => qr/^[a-z0-9]{2,10}$/,
                                                  -optional => 1,
                                                )
                                },
                     -values => List(-all => Whatever(-defined => 1)),
);

```
This should achieve the desired behaviour.

Best  regards, Laurent

**Comment by davewood** [comment]
hi damil, thank you for the response.

yes your workaround seems to solve my issue. small remark ... the error message is quite cryptic with the workaround.

```
details: $VAR1 = {
          '-values' => [
                         'Whatever: data defined/undefined',
                         undef
                       ]
        };
```

```
use strict;
use warnings;
use feature qw/say/;
use Data::Dumper;
use Data::Domain qw/:all/;

my $domain = Struct(
                     -exclude => '*',
                     -fields => {
                                  first_name=> String(
                                                  -regex => qr/^[a-z0-9]{2,8}$/,
                                                  -optional => 1,
                                                ),
                                  last_name => String(
                                                  -regex => qr/^[a-z0-9]{2,8}$/,
                                                  -optional => 1,
                                                ),
                                },
                     -values => List(-all => Whatever(-defined => 1)),
);

my @values = (
    undef,
    {},
    { first_name=> undef },
    { first_name=> 'a' },
    { first_name=> 'abc', last_name => undef },
    { first_name=> 'abc', last_name => 'def' },
    { first_name=> undef, last_name => 'def' },
);

for my $v (@values) {
    my $err = $domain->inspect($v);
    say '------------';
    print 'input:  ' . Dumper $v;
    print 'success: ';
    say $err ? 'NOTOK' : 'OK';
    print 'details: ' . Dumper $err if $err;
}
```

**Comment by davewood** [comment]
Did you make anote of this issue somewhere else when you closed it? The workaround you described, while helping, does not really solve the issue at hand and the feedback that you get from the error messages are very unintuitive for a workflow where say `{ first_name => 'required', last_name => 'required' }` is required for creating a resource and `{ first_name => 'optional_but_never_undef', last_name => 'optional_but_never_undef' }` for an update of an existing resource.

**Comment by damil** [comment]
Well, I would like to add a kind of -exists condition, but so far I didn't find a syntax that would be pleasant and implementable.
The best candidate would be something like 
```
Struct(-fields => {first_name => [-if_exists => String(...)],
                   last_name => ...})
```
but it is kind of awkward.

For the workaround, you could define your own message
```
my $domain = Struct(
  -exclude => '*',
  -fields => {
    name => String(-regex => qr/^[a-z0-9]{2,10}$/, -optional => 1),
  },
  -values => List(-all => Defined(-messages => "can't be undef")),
 );
```
but still this is not very satisfactory. 

Another workaround would be to use a lazy domain 
```
my $domain = Struct(
  -exclude => '*',
  -fields => {
    name => sub {my $context = shift;
                 exists $context->{flat}{name} ? String( -regex => qr/^[a-z0-9]{2,10}$/) : Whatever},

  },
 );
```

**Comment by damil** [comment]
ok reopened

**Comment by damil** [comment]
Sorry, I don't see the point. In the current version, fields are already mandatory by default. You have to explicitly say `-optional` for fields that are not mandatory. But this "optional" means that the field can either be absent or can be undef, which is what you want to avoid. So we need a syntax for specifying that we want an "exists" test.

**Comment by damil** [comment]
But I like your idea of having different domains for CREATE and for UPDATE -- just need to find the proper way to accomplish that

**Comment by damil** [comment]
Have a look at the last commits.
I added a -may_ignore option; it can take either an arrayref as you suggested, but also a regex or the '*' constant, like the -exclude option.  There are some examples in the doc.
Waiting for your feedback before publishing to CPAN

**Comment by davewood** [comment]
ill get back to you tomorrow probably, thank you for your effort.

**Comment by davewood** [comment]
using `-may_ignore` the error message for 

```Struct( last_name => String() )```

```{ last_name => undef }```

and 

```{ }```

is the same. 

> 'last_name' => 'String: undefined data'

I hope for a way to distinguish these to cases.

**Comment by davewood** [comment]
my bad, what I mean is that if you dont set `-may_ignore` Data::Domain cannot distinguish between undef and not-existing.

if you remove the `-may_ignore` setting from your example you get the following output

```
using Data::Domain version 1.13
normal : $VAR1 = {
          'last_name' => 'String: should match \'(?^:^[\\.a-z0-9-]{2,240}$)\''
        };

undefined : $VAR1 = {
          'last_name' => 'String: undefined data'
        };

absent : $VAR1 = {
          'last_name' => 'String: undefined data'
        };
```
 same error message for clearly different input.

**Comment by damil** [comment]
v1.13 is on CPAN
